import api from './api';
import type {
  BulkImportLog,
  PaginatedResponse,
  StudentProfile,
  StudentProfileDetail,
  StudentWriteRequest,
} from '@/types';

export interface StudentListParams {
  page?: number;
  search?: string;
  is_active?: boolean;
  school?: number;
  school_class?: number;
  section?: number;
  /**
   * Section LETTER, e.g. 'B'. Django-filter's related lookup, so the double underscore is
   * the actual query param. Distinct from `section` above, which is a section PK — the
   * letter filters across classes, the PK names one class's section.
   */
  section__name?: string;
  /**
   * EXACT Student ID match — not the substring behaviour of `search`. Used to resolve a
   * typed ID to one student; a substring match would let CSC001-001 also return
   * CSC001-0010. Double underscore because it is Django-filter's related lookup.
   */
  user__student_id?: string;
  ordering?: string;
}

export const studentsService = {
  async list(params: StudentListParams = {}): Promise<PaginatedResponse<StudentProfile>> {
    const { data } = await api.get<PaginatedResponse<StudentProfile>>('/students/', { params });
    return data;
  },

  async get(id: number): Promise<StudentProfileDetail> {
    const { data } = await api.get<StudentProfileDetail>(`/students/${id}/`);
    return data;
  },

  async create(payload: StudentWriteRequest): Promise<StudentProfileDetail> {
    const { data } = await api.post<StudentProfileDetail>('/students/', payload);
    return data;
  },

  /** Next free Student ID for a school. Server-side: only the DB knows what's taken. */
  async nextStudentId(school?: number): Promise<string> {
    const { data } = await api.get<{ student_id: string }>('/students/next-student-id/', {
      params: school ? { school } : undefined,
    });
    return data.student_id;
  },

  async update(id: number, payload: StudentWriteRequest): Promise<StudentProfileDetail> {
    const { data } = await api.put<StudentProfileDetail>(`/students/${id}/`, payload);
    return data;
  },

  async patch(id: number, payload: Partial<StudentWriteRequest>): Promise<StudentProfileDetail> {
    const { data } = await api.patch<StudentProfileDetail>(`/students/${id}/`, payload);
    return data;
  },

  async remove(id: number): Promise<void> {
    await api.delete(`/students/${id}/`);
  },

  /** Permanently delete the student (User + profile + related data). Irreversible. */
  async hardDelete(id: number): Promise<void> {
    await api.delete(`/students/${id}/hard-delete/`);
  },

  async bulkImport(formData: FormData): Promise<BulkImportLog> {
    const { data } = await api.post<BulkImportLog>('/students/bulk-import/', formData, {
      headers: { 'Content-Type': 'multipart/form-data' },
    });
    return data;
  },

  async importLogs(params: { page?: number } = {}): Promise<PaginatedResponse<BulkImportLog>> {
    const { data } = await api.get<PaginatedResponse<BulkImportLog>>('/students/import-logs/', { params });
    return data;
  },

  /** Delete one import history record. The students it created are unaffected. */
  async deleteImportLog(id: number): Promise<void> {
    await api.delete(`/students/import-logs/${id}/`);
  },

  /**
   * Download the import template.
   *
   * Generated by the server from the same column list the importer validates against, so
   * it can't drift out of step with what the importer accepts. Note the param is
   * `file_format`, not `format` — DRF reserves `format` for content negotiation.
   */
  async downloadImportTemplate(fileFormat: 'xlsx' | 'csv'): Promise<Blob> {
    const { data } = await api.get<Blob>('/students/import-template/', {
      params: { file_format: fileFormat },
      responseType: 'blob',
    });
    return data;
  },
};
