export type SchoolStatus = 'active' | 'inactive' | 'suspended';
export type SchoolBoard = 'state_board' | 'cbse' | 'matriculation';

export interface School {
  id: number;
  name: string;
  /**
   * The School ID (displayed under that name). Auto-generated by the server as a numeric
   * sequence (001, 002…) and never editable.
   */
  code: string;
  address: string;
  city: string;
  state: string;
  pincode: string;
  principal_name: string;
  /** The school's official CONTACT address. Never used for login or password reset. */
  official_email: string;
  contact_phone: string;
  logo: string | null;
  logo_url: string | null;
  status: SchoolStatus;
  /** The academic board the school is affiliated with. */
  school_board: SchoolBoard;
  /** Official government-issued school code. */
  school_code: string;
  created_by: number | null;
  created_at: string;
  updated_at: string;
  /**
   * One-time password-setup link for the School Admin. Present ONLY on the response to
   * creating a school — never on reads. Surface it to the CSC Admin so they can hand it
   * over; it is also emailed to the admin.
   */
  admin_setup_link?: string | null;
}

export interface SchoolListItem {
  id: number;
  name: string;
  code: string;
  city: string;
  state: string;
  official_email: string;
  status: SchoolStatus;
  school_board: SchoolBoard;
  school_code: string;
  user_count: number;
  teachers_count: number;
  students_count: number;
  logo_url?: string | null;
  created_at: string;
}

/** The School ID is server-generated, so it is deliberately absent here. */
export interface SchoolWriteRequest {
  name: string;
  address: string;
  city: string;
  state: string;
  pincode: string;
  principal_name: string;
  official_email: string;
  contact_phone: string;
  status: SchoolStatus;
  school_board: SchoolBoard;
  school_code: string;
}

/**
 * Creating a school also provisions its first School Admin, in one transaction.
 *
 * `admin_email` is that admin's LOGIN email and is stored on the User. It is entirely
 * separate from the school's `official_email`, which is only a contact address. The API
 * accepts these fields on create only and rejects them on update — editing a school must
 * never be able to change who can log into it.
 *
 * No password is chosen here: the admin sets their own via the one-time setup link the
 * create response returns (`School.admin_setup_link`) and that is emailed to them.
 */
export interface SchoolCreateRequest extends SchoolWriteRequest {
  admin_full_name: string;
  admin_email: string;
}

/** A school's School Admin account, from /schools/{id}/admins/. */
export interface SchoolAdmin {
  id: number;
  email: string;
  full_name: string;
  is_active: boolean;
  /** False until the admin uses their setup link to choose a password. */
  is_password_set: boolean;
  must_change_password: boolean;
  last_login: string | null;
}

export interface SchoolAdminWriteRequest {
  full_name?: string;
  email?: string;
  password?: string;
  is_active?: boolean;
}

export interface SchoolStats {
  school_admins: number;
  teachers: number;
  students: number;
  classes: number;
  subjects: number;
  tests: number;
}

export interface PlatformStats {
  total_schools: number;
  active_schools: number;
  total_users: number;
  total_school_admins: number;
  total_teachers: number;
  total_students: number;
  total_tests: number;
  exams_today: number;
}
