import { useEffect, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Check, Copy, ImagePlus, X } from 'lucide-react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { AxiosError } from 'axios';

import { AnimatedInput } from '@/components/ui/AnimatedInput';
import { Button } from '@/components/ui/Button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/Card';
import type { School, SchoolBoard, SchoolCreateRequest, SchoolStatus } from '@/types';
import { CustomSelect } from '@/components/ui/CustomSelect';
import { cn } from '@/lib/utils';

const TAMIL_NADU_DISTRICTS = [
  'Ariyalur',
  'Chengalpattu',
  'Chennai',
  'Coimbatore',
  'Cuddalore',
  'Dharmapuri',
  'Dindigul',
  'Erode',
  'Kallakurichi',
  'Kanchipuram',
  'Karur',
  'Krishnagiri',
  'Madurai',
  'Mayiladuthurai',
  'Nagapattinam',
  'Kanniyakumari',
  'Namakkal',
  'Perambalur',
  'Pudukottai',
  'Ramanathapuram',
  'Ranipet',
  'Salem',
  'Sivaganga',
  'Tenkasi',
  'Thanjavur',
  'Theni',
  'Thoothukudi',
  'Tiruchirappalli',
  'Tirunelveli',
  'Tirupathur',
  'Tiruppur',
  'Tiruvallur',
  'Tiruvannamalai',
  'Tiruvarur',
  'Vellore',
  'Viluppuram',
  'Virudhunagar',
  'The Nilgiris',
];

// No `code` field: the School ID is generated by the server from the school name and is
// never entered or edited by the CSC Admin.
const schoolSchema = z.object({
  name: z.string().min(2, 'Name is required'),
  address: z.string().min(3, 'Address is required'),
  city: z.string().min(2, 'City is required'),
  state: z.string().min(2, 'State is required').regex(/^[a-zA-Z\s]+$/, 'Only alphabetic characters are allowed'),
  pincode: z.string().regex(/^\d{4,10}$/, 'Pincode must be 4-10 digits'),
  // Optional in the SHARED schema so editing a legacy school with no recorded principal
  // isn't blocked. Add School (create) makes it required via createSchema below (item 4).
  principal_name: z.string().optional().default('').refine(val => !val || /^[a-zA-Z\s.]+$/.test(val), {
    message: 'Only alphabetic characters are allowed',
  }),
  official_email: z.string().email('Enter a valid email'),
  contact_phone: z.string().min(1, 'Phone is required').regex(/^\d*$/, 'Only numbers are allowed').refine(val => !val || val.length === 10, 'Contact phone number must be exactly 10 digits'),
  lan: z.string().regex(/^\d*$/, 'Only numbers are allowed').optional().default(''),
  status: z.enum(['active', 'inactive', 'suspended']),
  school_board: z.enum(['state_board', 'cbse', 'matriculation'], {
    errorMap: () => ({ message: 'School Board is required' }),
  }),
  school_code: z.string().min(1, 'School Code is required').regex(/^\d+$/, 'Only numbers are allowed'),
});

/**
 * On CREATE the form also provisions the school's first School Admin. These fields do not
 * exist in edit mode: a School Admin's login email is their credential and must never be
 * changeable by editing the school's contact details.
 */
const schoolAdminSchema = z.object({
  admin_email: z.string().email('Enter a valid login email'),
});

// Add School requires every field, including Principal name (item 4). Edit uses the base
// schoolSchema, where principal_name stays optional.
const createSchema = schoolSchema.merge(schoolAdminSchema).extend({
  principal_name: z.string().min(2, 'Principal name is required').regex(/^[a-zA-Z\s.]+$/, 'Only alphabetic characters are allowed'),
});

export type SchoolFormValues = z.infer<typeof createSchema>;

interface SchoolFormProps {
  initial?: School;
  /**
   * Receives SchoolCreateRequest. In edit mode the admin_* keys are omitted from the object
   * at runtime (the API rejects them on update) — SchoolCreateRequest extends
   * SchoolWriteRequest, so an update handler can accept it directly.
   */
  onSubmit: (values: SchoolCreateRequest, logo?: File | null) => Promise<School>;
  submitLabel: string;
  title: string;
}

const MAX_LOGO_BYTES = 2 * 1024 * 1024;
const ACCEPTED_LOGO_TYPES = ['image/png', 'image/jpeg'];

const getLogoUrl = (url: string | null) => {
  if (!url) return null;
  if (url.startsWith('http://') || url.startsWith('https://') || url.startsWith('blob:') || url.startsWith('data:')) return url;
  const base = import.meta.env.VITE_API_URL || 'http://localhost:8080';
  return `${base}${url}`;
};

export function SchoolForm({ initial, onSubmit, submitLabel, title }: SchoolFormProps) {
  const navigate = useNavigate();
  // Edit mode validates school fields only — the admin fields aren't rendered, so
  // requiring them would make the form unsubmittable.
  const isEdit = !!initial;
  const activeSchema = isEdit ? schoolSchema : createSchema;
  const [formError, setFormError] = useState<string | null>(null);
  const [logoFile, setLogoFile] = useState<File | null>(null);
  const [logoPreview, setLogoPreview] = useState<string | null>(() => getLogoUrl(initial?.logo_url ?? null));
  const [logoError, setLogoError] = useState<string | null>(null);
  const logoInputRef = useRef<HTMLInputElement>(null);
  // After a successful create, hold the new admin's details + one-time setup link so the
  // CSC Admin can copy it. Non-null switches the form over to the success panel.
  const [created, setCreated] = useState<{
    school: School;
    adminEmail: string;
    setupLink: string | null;
  } | null>(null);
  const [copied, setCopied] = useState(false);

  // Revoke the object URL we create for the preview to avoid leaking it.
  useEffect(() => {
    if (!logoFile) return;
    const url = URL.createObjectURL(logoFile);
    setLogoPreview(url);
    return () => URL.revokeObjectURL(url);
  }, [logoFile]);

  const handleLogoChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setLogoError(null);
    const file = e.target.files?.[0] ?? null;
    if (!file) {
      setLogoFile(null);
      return;
    }
    if (!ACCEPTED_LOGO_TYPES.includes(file.type)) {
      setLogoError('Logo must be a PNG, JPG, or JPEG image.');
      e.target.value = '';
      return;
    }
    if (file.size > MAX_LOGO_BYTES) {
      setLogoError('Logo must be 2MB or smaller.');
      e.target.value = '';
      return;
    }
    setLogoFile(file);
  };

  const clearLogo = () => {
    setLogoFile(null);
    setLogoError(null);
    setLogoPreview(getLogoUrl(initial?.logo_url ?? null));
    if (logoInputRef.current) logoInputRef.current.value = '';
  };

  const {
    register,
    handleSubmit,
    setError,
    reset,
    setValue,
    watch,
    formState: { errors, isSubmitting },
  } = useForm<SchoolFormValues>({
    resolver: zodResolver(activeSchema),
    defaultValues: {
      name: '',
      address: '',
      city: '',
      state: 'Tamil Nadu',
      pincode: '',
      principal_name: '',
      official_email: '',
      contact_phone: '',
      lan: '',
      status: 'active' as SchoolStatus,
      school_board: 'state_board' as SchoolBoard,
      school_code: '',
      admin_email: '',
    },
  });

  useEffect(() => {
    if (initial) {
      reset({
        name: initial.name,
        address: initial.address,
        city: initial.city,
        state: initial.state,
        pincode: initial.pincode,
        principal_name: initial.principal_name ?? '',
        official_email: initial.official_email,
        contact_phone: initial.contact_phone,
        lan: initial.lan ?? '',
        status: initial.status,
        school_board: initial.school_board ?? 'state_board',
        school_code: initial.school_code ?? '',
        // Never populated in edit mode — the admin account is managed separately.
        admin_email: '',
      });
      // Show the saved logo as the preview when no new file has been picked yet.
      setLogoFile(null);
      setLogoPreview(getLogoUrl(initial.logo_url ?? null));
    }
  }, [initial, reset]);

  const submit = async (values: SchoolFormValues) => {
    setFormError(null);
    try {
      const { admin_email, ...schoolFields } = values;
      const payload = {
        ...schoolFields,
        principal_name: values.principal_name ?? '',
        // Admin fields go out on create only. The API rejects them on update, so sending
        // them (even blank) while editing would fail the request.
        ...(isEdit ? {} : { admin_full_name: values.principal_name ?? '', admin_email }),
      };

      const saved = await onSubmit(payload as SchoolCreateRequest, logoFile);
      if (!isEdit) {
        // Stay on the page to show the one-time setup link the CSC Admin hands over.
        setCreated({
          school: saved,
          adminEmail: admin_email,
          setupLink: saved.admin_setup_link ?? null,
        });
        return;
      }
      navigate(`/admin/schools/${saved.id}`);
    } catch (err) {
      if (err instanceof AxiosError && err.response?.data && typeof err.response.data === 'object') {
        const data = err.response.data as Record<string, string | string[] | undefined>;
        let handled = false;
        if (!isEdit && data.admin_full_name) {
          const message = Array.isArray(data.admin_full_name)
            ? data.admin_full_name.join(' ')
            : String(data.admin_full_name);
          setError('principal_name', { type: 'server', message });
          handled = true;
        }
        (Object.keys(activeSchema.shape) as (keyof SchoolFormValues)[]).forEach((field) => {
          const value = data[field];
          if (value) {
            const message = Array.isArray(value) ? value.join(' ') : value;
            setError(field, { type: 'server', message });
            handled = true;
          }
        });
        if (!handled) {
          const detail = data.detail;
          setFormError(typeof detail === 'string' ? detail : 'Save failed.');
        }
      } else {
        setFormError('Something went wrong. Please try again.');
      }
    }
  };

  const copySetupLink = async () => {
    if (!created?.setupLink) return;
    try {
      await navigator.clipboard.writeText(created.setupLink);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      setFormError('Could not copy the link — select and copy it manually.');
    }
  };

  if (created) {
    return (
      <Card className="max-w-3xl bg-[#F1EFFE]">
        <CardHeader>
          <CardTitle>School created</CardTitle>
        </CardHeader>
        <CardContent className="space-y-5">
          <p className="text-sm text-muted-foreground">
            <span className="font-medium text-foreground">{created.school.name}</span> was
            created and its School Admin account was provisioned for{' '}
            <span className="font-medium text-foreground">{created.adminEmail}</span>.
          </p>

          <div className="rounded-xl border-2 border-input p-4 space-y-3">
            <div>
              <h3 className="text-sm font-semibold">Password setup link</h3>
              <p className="text-xs text-muted-foreground">
                Send this to the School Admin so they can set their own password. It has also
                been emailed to them and expires in 1 hour. The admin cannot log in until they
                use it.
              </p>
            </div>

            {created.setupLink ? (
              <div className="flex items-center gap-2">
                <input
                  readOnly
                  value={created.setupLink}
                  onFocus={(e) => e.target.select()}
                  className="flex-1 min-w-0 rounded-md border border-input bg-muted/40 px-3 py-2 text-sm font-mono"
                />
                <Button type="button" variant="outline" onClick={copySetupLink} className="shrink-0">
                  {copied ? (
                    <>
                      <Check className="mr-1 h-4 w-4" /> Copied
                    </>
                  ) : (
                    <>
                      <Copy className="mr-1 h-4 w-4" /> Copy
                    </>
                  )}
                </Button>
              </div>
            ) : (
              <p className="text-sm text-destructive">
                The setup link could not be generated. Open the school's detail page and use
                the School Admin section to resend it.
              </p>
            )}
          </div>

          <div className="flex justify-end gap-2">
            <Button
              type="button"
              variant="outline"
              onClick={() => {
                // Same route — navigating wouldn't remount, so clear the form state here.
                reset();
                setLogoFile(null);
                setLogoPreview(null);
                setFormError(null);
                setCreated(null);
              }}
            >
              Create another
            </Button>
            <Button
              type="button"
              variant="gradient"
              onClick={() => navigate(`/admin/schools/${created.school.id}`)}
            >
              Go to school
            </Button>
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card className="max-w-3xl bg-[#F1EFFE]">
      <CardHeader>
        <CardTitle>{title}</CardTitle>
      </CardHeader>
      <CardContent>
        <form onSubmit={handleSubmit(submit)} className="grid grid-cols-1 md:grid-cols-2 gap-4" noValidate>
          <AnimatedInput
            label="School name"
            requiredMark
            placeholder="St. Joseph's Higher Secondary"
            error={errors.name?.message}
            {...register('name')}
          />
          {isEdit ? (
            <div className="space-y-1">
              <label className="block text-sm font-medium">School ID</label>
              <p className="px-4 py-3 rounded-xl border-2 border-input bg-muted/40 font-mono text-sm">
                {initial.code}
              </p>
              <p className="text-xs text-muted-foreground">
                Auto-generated and permanent — student login IDs are built from it.
              </p>
            </div>
          ) : (
            <div className="space-y-1">
              <label className="block text-sm font-medium">School ID</label>
              <p className="px-4 py-3 rounded-xl border-2 border-dashed border-input bg-muted/40 text-sm text-muted-foreground">
                Generated automatically
              </p>
              <p className="text-xs text-muted-foreground">
                Auto-generated numeric sequence, e.g. 001, 002, 003.
              </p>
            </div>
          )}
          <div className="md:col-span-2">
            <AnimatedInput
              label="Address"
              requiredMark
              placeholder="123 School Lane"
              error={errors.address?.message}
              {...register('address')}
            />
          </div>
          <div className="space-y-1">
            <label className="block text-sm font-medium" htmlFor="city">
              City
              <span className="ml-0.5 text-destructive">*</span>
            </label>
            <input type="hidden" {...register('city')} />
            <CustomSelect
              options={TAMIL_NADU_DISTRICTS.map((d) => ({ value: d, label: d }))}
              value={watch('city') ?? ''}
              onChange={(val) => setValue('city', val, { shouldValidate: true })}
              placeholder="Select City"
              searchable={true}
              searchPlaceholder="Search districts..."
              containerClassName="w-full"
              className={cn(
                errors.city && "border-destructive focus:border-destructive"
              )}
            />
            {errors.city && <p className="text-sm text-destructive">{errors.city.message}</p>}
          </div>
          <AnimatedInput
            label="State"
            requiredMark
            error={errors.state?.message}
            {...register('state', {
              onChange: (e) => {
                e.target.value = e.target.value.replace(/[^a-zA-Z\s]/g, '');
              },
            })}
          />
          <AnimatedInput
            label="Pincode"
            requiredMark
            error={errors.pincode?.message}
            {...register('pincode', {
              onChange: (e) => {
                e.target.value = e.target.value.replace(/\D/g, '');
              },
            })}
          />
          <AnimatedInput
            label="Principal name"
            requiredMark={!isEdit}
            error={errors.principal_name?.message}
            {...register('principal_name', {
              onChange: (e) => {
                e.target.value = e.target.value.replace(/[^a-zA-Z\s.]/g, '');
              },
            })}
          />
          <AnimatedInput
            label="LAN"
            placeholder="e.g. 044-2432424"
            error={errors.lan?.message}
            {...register('lan', {
              onChange: (e) => {
                e.target.value = e.target.value.replace(/\D/g, '');
              },
            })}
          />
          <AnimatedInput
            label="Contact phone"
            requiredMark
            maxLength={10}
            error={errors.contact_phone?.message}
            {...register('contact_phone', {
              onChange: (e) => {
                e.target.value = e.target.value.replace(/\D/g, '');
              },
            })}
          />
          <div className="space-y-1">
            <label className="block text-sm font-medium" htmlFor="status">
              Status
              <span className="ml-0.5 text-destructive">*</span>
            </label>
            <input type="hidden" {...register('status')} />
            <CustomSelect
              options={[
                { value: 'active', label: 'Active' },
                { value: 'inactive', label: 'Inactive' },
                { value: 'suspended', label: 'Suspended' },
              ]}
              value={watch('status') ?? 'active'}
              onChange={(val) => setValue('status', val as 'active' | 'inactive' | 'suspended')}
              containerClassName="w-full"
            />
            {errors.status && <p className="text-sm text-destructive">{errors.status.message}</p>}
          </div>
          <div className="space-y-1">
            <label className="block text-sm font-medium" htmlFor="school_board">
              School Board
              <span className="ml-0.5 text-destructive">*</span>
            </label>
            <input type="hidden" {...register('school_board')} />
            <CustomSelect
              options={[
                { value: 'state_board', label: 'State Board' },
                { value: 'cbse', label: 'CBSE Board' },
                { value: 'matriculation', label: 'Matriculation' },
              ]}
              value={watch('school_board') ?? 'state_board'}
              onChange={(val) => setValue('school_board', val as SchoolBoard)}
              containerClassName="w-full"
            />
            {errors.school_board && <p className="text-sm text-destructive">{errors.school_board.message}</p>}
          </div>
          <AnimatedInput
            label="School Code"
            requiredMark
            placeholder="e.g. 33010100101"
            error={errors.school_code?.message}
            {...register('school_code', {
              onChange: (e) => {
                e.target.value = e.target.value.replace(/\D/g, '');
              },
            })}
          />
          <div className="space-y-1">
            <AnimatedInput
              label="Official school email"
              requiredMark
              type="email"
              placeholder="office@school.edu"
              error={errors.official_email?.message}
              {...register('official_email')}
            />
            {!errors.official_email && (
              <p className="text-xs text-muted-foreground">
                This email is used only for communication.
              </p>
            )}
          </div>

          <div className="md:col-span-2 space-y-2">
            <label className="block text-sm font-medium">School logo</label>
            <div className="flex items-center gap-4">
              <div className="h-20 w-20 flex-shrink-0 rounded-xl border-2 border-input bg-muted/40 overflow-hidden flex items-center justify-center">
                {logoPreview ? (
                  <img
                    src={logoPreview}
                    alt="School logo preview"
                    className="h-full w-full object-contain"
                  />
                ) : (
                  <ImagePlus className="h-7 w-7 text-muted-foreground" />
                )}
              </div>
              <div className="space-y-1">
                <input
                  ref={logoInputRef}
                  type="file"
                  accept="image/png,image/jpeg,.png,.jpg,.jpeg"
                  onChange={handleLogoChange}
                  className="block text-sm text-muted-foreground file:mr-3 file:rounded-lg file:border-0 file:bg-primary file:px-4 file:py-2 file:text-sm file:font-medium file:text-primary-foreground hover:file:bg-primary/90"
                />
                <p className="text-xs text-muted-foreground">PNG, JPG, or JPEG · max 2MB</p>
                {(logoFile || (logoPreview && logoPreview !== initial?.logo_url)) && (
                  <button
                    type="button"
                    onClick={clearLogo}
                    className="inline-flex items-center gap-1 text-xs text-destructive hover:underline"
                  >
                    <X className="h-3 w-3" /> Remove selected logo
                  </button>
                )}
              </div>
            </div>
            {logoError && <p className="text-sm text-destructive">{logoError}</p>}
          </div>

          {!isEdit && (
            <div className="md:col-span-2 mt-2 rounded-xl border-2 border-input p-4 space-y-4">
              <div>
                <h3 className="text-sm font-semibold">School Admin Information</h3>
                <p className="text-xs text-muted-foreground">
                  The account that will manage this school. Created together with the school —
                  if anything fails, nothing is saved. No password is set here: the admin gets
                  a one-time setup link (shown after you create the school and emailed to them)
                  to choose their own password.
                </p>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="space-y-1">
                  <AnimatedInput
                    label="Principal login email"
                    requiredMark
                    type="email"
                    placeholder="admin@school.edu"
                    error={errors.admin_email?.message}
                    {...register('admin_email')}
                  />
                  {!errors.admin_email && (
                    <p className="text-xs text-muted-foreground">
                      This email is used for login, the setup link, and password reset.
                    </p>
                  )}
                </div>
              </div>
            </div>
          )}

          {isEdit && (
            <p className="md:col-span-2 text-xs text-muted-foreground">
              The Principal's login email is not editable here — manage it from the school's
              detail page under School Admin.
            </p>
          )}

          {formError && (
            <div className="md:col-span-2 text-sm text-destructive bg-destructive/10 border border-destructive/30 rounded-md px-3 py-2">
              {formError}
            </div>
          )}

          <div className="md:col-span-2 flex justify-end gap-2 pt-2">
            <Button type="button" variant="outline" onClick={() => navigate('/admin/schools')}>
              Cancel
            </Button>
            <Button type="submit" variant="gradient" disabled={isSubmitting}>
              {isSubmitting ? 'Saving…' : submitLabel}
            </Button>
          </div>
        </form>
      </CardContent>
    </Card>
  );
}
